description: >
  Executor for trivy
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: "2021.07"
    description: >
      Tag for 'cimg/base' docker container
    type: string
